spring:
  application:
    name: spd-agenda-vacinacao
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: myuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
        time_zone: UTC
server:
  error:
    include-stacktrace: never
